### ISSUE TITLE
报错 strtolower() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by September999999999** [guanguans/dcat-login-captcha#15]
`{
    "message": "strtolower() expects parameter 1 to be string, array given",
    "exception": "ErrorException",
    "file": "/www/backend-service/vendor/gregwar/captcha/src/Gregwar/Captcha/PhraseBuilder.php",
    "line": 65,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/gregwar/captcha/src/Gregwar/Captcha/PhraseBuilder.php",
            "line": 65,
            "function": "strtolower"
        },
        {
            "file": "/www/backend-service/vendor/gregwar/captcha/src/Gregwar/Captcha/PhraseBuilder.php",
            "line": 73,
            "function": "doNiceize",
            "class": "Gregwar\\Captcha\\PhraseBuilder",
            "type": "::"
        },
        {
            "file": "/www/backend-service/vendor/guanguans/dcat-login-captcha/src/helpers.php",
            "line": 23,
            "function": "comparePhrases",
            "class": "Gregwar\\Captcha\\PhraseBuilder",
            "type": "::"
        },
        {
            "file": "/www/backend-service/vendor/guanguans/dcat-login-captcha/src/LoginCaptchaServiceProvider.php",
            "line": 109,
            "function": "login_captcha_check"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Validation/Validator.php",
            "line": 1495,
            "function": "Guanguans\\DcatLoginCaptcha\\{closure}",
            "class": "Guanguans\\DcatLoginCaptcha\\LoginCaptchaServiceProvider",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Validation/Validator.php",
            "line": 1529,
            "function": "callExtension",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Validation/Validator.php",
            "line": 610,
            "function": "__call",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Validation/Validator.php",
            "line": 416,
            "function": "validateAttribute",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Validation/Validator.php",
            "line": 447,
            "function": "passes",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/guanguans/dcat-login-captcha/src/BootingHandler.php",
            "line": 36,
            "function": "fails",
            "class": "Illuminate\\Validation\\Validator",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php",
            "line": 404,
            "function": "__invoke",
            "class": "Guanguans\\DcatLoginCaptcha\\BootingHandler",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php",
            "line": 249,
            "function": "Illuminate\\Events\\{closure}",
            "class": "Illuminate\\Events\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php",
            "line": 261,
            "function": "dispatch",
            "class": "Illuminate\\Events\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/dcat/laravel-admin/src/Admin.php",
            "line": 321,
            "function": "__callStatic",
            "class": "Illuminate\\Support\\Facades\\Facade",
            "type": "::"
        },
        {
            "file": "/www/backend-service/vendor/dcat/laravel-admin/src/Http/Middleware/Bootstrap.php",
            "line": 52,
            "function": "callBooting",
            "class": "Dcat\\Admin\\Admin",
            "type": "::"
        },
        {
            "file": "/www/backend-service/vendor/dcat/laravel-admin/src/Http/Middleware/Bootstrap.php",
            "line": 16,
            "function": "fireEvents",
            "class": "Dcat\\Admin\\Http\\Middleware\\Bootstrap",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Dcat\\Admin\\Http\\Middleware\\Bootstrap",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/dcat/laravel-admin/src/Http/Middleware/Pjax.php",
            "line": 22,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Dcat\\Admin\\Http\\Middleware\\Pjax",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/dcat/laravel-admin/src/Http/Middleware/Authenticate.php",
            "line": 26,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Dcat\\Admin\\Http\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 50,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 78,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 121,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 64,
            "function": "handleStatefulRequest",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 67,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/dcat/laravel-admin/src/Http/Middleware/Application.php",
            "line": 15,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Dcat\\Admin\\Http\\Middleware\\Application",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 723,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 698,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 651,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 167,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php",
            "line": 31,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php",
            "line": 40,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php",
            "line": 86,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/fruitcake/laravel-cors/src/HandleCors.php",
            "line": 38,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php",
            "line": 39,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Http\\Middleware\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 142,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/www/backend-service/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 111,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/www/backend-service/public/index.php",
            "line": 52,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}`

**Comment by guanguans** [comment]
@September999999999 是第一次安装吗？还是更新到新版本报的这个错误。

**Comment by September999999999** [comment]
生产环境还在正常跑，我电脑重装完，composer install 就出现这个问题了

> @September999999999 是第一次安装吗？还是更新到新版本报的这个错误。

**Comment by guanguans** [comment]
@September999999999
将 `admin_settings` 表 `slug` 为 `guanguans:dcat-login-captcha` 的记录删除掉，重新安装试一下。

**Comment by guanguans** [comment]
@September999999999 麻烦你看一下你目前是哪个版本。如果是 `v1.0.11`、`v1.0.12` 就按照我上面说的步骤是一下。如果是之前的版本，应该是没什么问题的。主要是确保 `phrase_session_key` 的变化。详情可以看 这一次提交 [de2f3337](https://github.com/guanguans/dcat-login-captcha/commit/de2f3337c59e4475a87ff2b06c44142fb8cda8af)

**Comment by guanguans** [comment]
> 试过了一样的，我报错具体行（/www/backend-service/vendor/gregwar/captcha/src/Gregwar/Captcha/PhraseBuilder.php 65行）拿到的数据 打印出来是这样的  `array:5 [
> 
>   "admin" => array:1 [
> 
>     "prev" => []
> 
>   ]
> 
>   "_flash" => array:2 [
> 
>     "new" => []
> 
>     "old" => []
> 
>   ]
> 
>   "_token" => "IJjn7ceVEupBNZ0vPLh6GaY0JLfXSA4au6zZ1ygY"
> 
>   "_previous" => array:1 [
> 
>     "url" => "http://127.0.0.1:20018/admin/captcha/generate?random=9fnvnFUjhSimetyv"
> 
>   ]
> 
>   "" => "PdXP"
> 
> ]` @guanguans 

还是不行吗？

**Comment by September999999999** [comment]
> > 试过了一样的，我报错具体行（/www/backend-service/vendor/gregwar/captcha/src/Gregwar/Captcha/PhraseBuilder.php 65行）拿到的数据 打印出来是这样的  `array:5 [
> > "admin" => array:1 [
> > ```
> > "prev" => []
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ]
> > "_flash" => array:2 [
> > ```
> > "new" => []
> > 
> > "old" => []
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ]
> > "_token" => "IJjn7ceVEupBNZ0vPLh6GaY0JLfXSA4au6zZ1ygY"
> > "_previous" => array:1 [
> > ```
> > "url" => "http://127.0.0.1:20018/admin/captcha/generate?random=9fnvnFUjhSimetyv"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ]
> > "" => "PdXP"
> > ]` @guanguans
> 
> 还是不行吗？

不行..,我生产环境执行composer update 发现也产生了同样的问题，周一我贴下那些包升级了

**Comment by guanguans** [comment]
@September999999999

麻烦提供一下下面打印的结果

```php
dump($key = LoginCaptchaServiceProvider::setting('captcha_phrase_session_key'), Session::get($key));
```

以及插件配置的数据

```sql
SELECT * FROM admin_settings WHERE slug='guanguans:dcat-login-captcha';
```

**Comment by September999999999** [comment]
> @September999999999
> 
> 麻烦提供一下下面打印的结果
> 
> ```
> dump($key = LoginCaptchaServiceProvider::setting('captcha_phrase_session_key'), Session::get($key));
> ```
> 
> 以及插件配置的数据
> 
> ```sql
> SELECT * FROM admin_settings WHERE slug='guanguans:dcat-login-captcha';
> ```


```
打印的结果
null
array:5 [[▼]()
  "admin" => array:1 [[▼]()
    "prev" => []
  ]
  "_flash" => array:2 [[▼]()
    "new" => []
    "old" => []
  ]
  "_token" => "xWaLXF9wrpnmyASFnzLr8cWFqEqCCDr6P43WZwY4"
  "_previous" => array:1 [[▼]()
    "url" => "http://127.0.0.1:20018/oss/test"
  ]
  "" => "O8WV"
]
```

```
插件配置的数据
mysql> SELECT * FROM admin_settings WHERE slug='guanguans:dcat-login-captcha';
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| slug                         | value                                                                                                                                                                                                | created_at          | updated_at          |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
| guanguans:dcat-login-captcha | {"length":4,"charset":"abcdefghijklmnpqrstuvwxyz23456789ABCDEFGHIJKLMNOPQRSTUVWXYZ","width":150,"height":43,"type":"png","font":null,"fingerprint":null,"phrase_session_key":"login_captcha_phrase"} | 2022-04-07 16:20:01 | 2022-04-07 16:20:01 |
+------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------+
1 row in set (0.04 sec)
```

**Comment by guanguans** [comment]
@September999999999 

你数据库的配置没有更新，还是旧版本的 `phrase_session_key`
你执行一下

```sql
UPDATE `admin_settings` 
SET `value` = REPLACE ( `value`, 'phrase_session_key', 'captcha_phrase_session_key' ) 
WHERE slug = 'guanguans:dcat-login-captcha';
```

或者将数据库中的配置 `phrase_session_key` 更新为 `captcha_phrase_session_key`

**Comment by September999999999** [comment]
> ```sql
> UPDATE `admin_settings` 
> SET `value` = REPLACE ( `value`, 'phrase_session_key', 'captcha_phrase_session_key' ) 
> WHERE slug = 'guanguans:dcat-login-captcha';
> ```

确实好了，感谢大佬！
