### ISSUE TITLE
开启后无法使用路由

### ISSUE THREAD

**Issue by jin-null** [guanguans/dcat-login-captcha#16]
laravel 报错 Route [dcat.admin.captcha.generate] not defined.
环境版本
php7.4
laravel 8.65
dcat 2.0

**Comment by guanguans** [comment]
@jin-null dcat 的具体版本号是多少?

**Comment by guanguans** [comment]
没有复现你的问题

![image](https://user-images.githubusercontent.com/22309277/175854222-c3fdf53c-7f6a-4c4b-950e-08d089bd629a.png)
