### ISSUE TITLE
laravel 9,php8.1 dcat2.*安装最新的2.*版本报错

### ISSUE THREAD

**Issue by ljyljy0211** [guanguans/dcat-login-captcha#39]
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Dcat\Admin\Exception\RuntimeException

  Error extension "Guanguans\DcatLoginCaptcha\LoginCaptchaServiceProvider"

  at vendor/dcat/laravel-admin/src/Extend/Manager.php:298
    294▕         if (! $serviceProvider->getName()) {
    295▕             $json = dirname(dirname(Helper::guessClassFileName($serviceProvider))).'/composer.json';
    296▕
    297▕             if (! is_file($json)) {
  ➜ 298▕                 throw new RuntimeException(sprintf('Error extension "%s"', get_class($serviceProvider)));
    299▕             }
    300▕
    301▕             $serviceProvider->withComposerProperty(Composer::parse($json));
    302▕         }

      +9 vendor frames
  10  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Guanguans\DcatLoginCaptcha\LoginCaptchaServiceProvider))

      +5 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by guanguans** [comment]
@ljyljy0211 暂且退回v1版本。
这个问题比较奇怪。安装后 composer.json 文件会丢失，目前还没找到什么原因。

**Comment by guanguans** [comment]
@ljyljy0211 可能是composer缓存的原因导致的。加上 `--prefer-source` 选项试试

```shell
composer require guanguans/dcat-login-captcha:^2.0 --prefer-source -v
```

**Comment by ljyljy0211** [comment]
@guanguans 我发现了，如果composer用的是阿里云的源，就有问题，如果用官方源就没有问题

**Comment by guanguans** [comment]
@ljyljy0211 麻烦你看下阿里云的源下的 composer.json 文件是不是丢失了。

<img width="1148" alt="image" src="https://github.com/guanguans/dcat-login-captcha/assets/22309277/2957303c-d704-4245-940b-e0bf8a253533">

**Comment by ljyljy0211** [comment]
@guanguans 用阿里云的话composer.json的确丢了

**Comment by guanguans** [comment]
@ljyljy0211 好的，挺坑的，还是切官方源吧。

**Comment by senkorl** [comment]
> @ljyljy0211 好的，挺坑的，还是切官方源吧。

即使是官方源，没有加上 `--prefer-source`选项也是缺少composer.json文件，这体现在拉项目`composer install`的时候，必然报错。
