### ISSUE TITLE
composer require guanguans/dcat-login-captcha --prefer-source -v 提示找不到文件

### ISSUE THREAD

**Issue by liumiao1128** [guanguans/dcat-login-captcha#42]
composer 安装扩展的审核，提示 Error extension "Guanguans\DcatLoginCaptcha\LoginCaptchaServiceProvider"
<img width="1421" alt="Snipaste_2024-01-08_14-26-34" src="https://github.com/guanguans/dcat-login-captcha/assets/20535083/6fd4d10e-d37a-4ace-a514-fe2cc70c0cb7">

**Comment by guanguans** [comment]
@liumiao1128 看这个 issue https://github.com/guanguans/dcat-login-captcha/issues/39

**Comment by liumiao1128** [comment]
的确是阿里云源的问题，真的是好气人哦
