### ISSUE TITLE
当修改配置文件的ADMIN_ROUTE_PREFIX为其他时，登录时，验证码不显示

### ISSUE THREAD

**Issue by jiangzhangy** [guanguans/dcat-login-captcha#8]
版本：Dcat Admin  ·  v2.1.2-beta    本插件：1.0.7
当我修改 ADMIN_ROUTE_PREFIX=aaa 时，验证码失效。
![image](https://user-images.githubusercontent.com/29587925/133014402-ea02c565-2cd9-44bc-a7a1-f3229bb8e2f0.png)

**Comment by guanguans** [comment]
@jiangzhangy

已修复([commit](https://github.com/guanguans/dcat-login-captcha/commit/a4ad40a1b1bb4e4e93559fefbf2ad9c6d843d99b))，请更新至当前最新版本(1.0.8)。
